import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Boxes, MapPin, Plus, Search, Route, Gauge, Trash2 } from 'lucide-react';
import { salvarCEO as salvarCEOFirebase, listarCEOs, excluirCEO } from '../services/ceos';
import './CEOs.css';
import { useAuth } from '../context/AuthContext';

const vazio={nome:'',tipo:'CEO 24FO',rota:'',status:'Operacional',km:'',latitude:'',longitude:'',referencia:'',maps:'',observacao:'',foto:''};
function fotoParaBase64(arquivo){return new Promise((resolve,reject)=>{const leitor=new FileReader();leitor.onload=()=>resolve(leitor.result);leitor.onerror=reject;leitor.readAsDataURL(arquivo);})}
export default function CEOs(){
 const {isAdmin}=useAuth();
 const [params]=useSearchParams(); const rotaUrl=params.get('rota')||'';
 const [ceos,setCeos]=useState([]),[pesquisa,setPesquisa]=useState(''),[modal,setModal]=useState(false),[form,setForm]=useState({...vazio,rota:rotaUrl}),[carregando,setCarregando]=useState(true);
 async function carregar(){try{setCeos(await listarCEOs())}catch(e){console.error(e);alert('Não foi possível carregar as CEOs do Firebase. Verifique a internet e a configuração.')}finally{setCarregando(false)}}
 useEffect(()=>{carregar()},[]);
 async function salvar(e){e.preventDefault();if(!form.nome.trim())return alert('Informe o nome da CEO.');try{const dados={...form};if(form.foto instanceof File){if(form.foto.size>700*1024)return alert('A foto da CEO deve ter no máximo 700 KB.');dados.foto=await fotoParaBase64(form.foto);dados.fotoNome=form.foto.name;}await salvarCEOFirebase(dados);setForm({...vazio,rota:rotaUrl});setModal(false);await carregar()}catch(e){console.error(e);alert('Erro ao salvar a CEO.')}}
 async function remover(id){if(!isAdmin){window.dispatchEvent(new Event('open-admin-login'));return;}if(!confirm('Excluir esta CEO?'))return;try{await excluirCEO(id);await carregar()}catch{alert('Não foi possível excluir.')}}
 const filtradas=useMemo(()=>ceos.filter(c=>{const q=pesquisa.toLowerCase();const texto=`${c.nome} ${c.tipo} ${c.rota} ${c.referencia}`.toLowerCase();return texto.includes(q)&&(!rotaUrl||c.rota===rotaUrl)}),[ceos,pesquisa,rotaUrl]);
 return <div className="ceos-page">
  <header className="ceos-header"><div><span className="pagina-identificacao">DOCUMENTAÇÃO DA REDE</span><h1>Caixas de Emenda Óptica</h1><p>CEOs, localização, capacidade, rota e documentação relacionada.</p></div>{isAdmin&&<button className="botao-primario" onClick={()=>setModal(true)}><Plus size={18}/> Nova CEO</button>}</header>
  <div className="ceos-resumo"><div><Boxes/><span><strong>{ceos.length}</strong>Total de CEOs</span></div><div><Route/><span><strong>{new Set(ceos.map(c=>c.rota).filter(Boolean)).size}</strong>Rotas atendidas</span></div><div><Gauge/><span><strong>{ceos.filter(c=>c.status==='Operacional').length}</strong>Operacionais</span></div></div>
  <div className="ceos-toolbar"><Search size={18}/><input placeholder="Pesquisar por nome, rota, tipo ou referência..." value={pesquisa} onChange={e=>setPesquisa(e.target.value)}/><span>{filtradas.length} resultado(s)</span></div>
  {carregando?<div className="ceos-empty">Carregando CEOs...</div>:filtradas.length===0?<div className="ceos-empty"><Boxes size={40}/><h3>Nenhuma CEO encontrada</h3><p>Cadastre uma CEO ou altere a pesquisa.</p></div>:<div className="ceos-grid">{filtradas.map(ceo=><article className="ceo-card" key={ceo.id}>{ceo.foto&&<img className="ceo-card-foto" src={ceo.foto} alt={ceo.nome}/>}<div className="ceo-card-top"><div className="ceo-icon"><Boxes size={23}/></div><span className={`ceo-status ${String(ceo.status).toLowerCase().replace('ç','c')}`}>{ceo.status||'Operacional'}</span></div><h2>{ceo.nome}</h2><p className="ceo-rota"><Route size={15}/>{ceo.rota||'Rota não informada'}</p><div className="ceo-info"><div><span>Tipo</span><strong>{ceo.tipo||'—'}</strong></div><div><span>KM</span><strong>{ceo.km||'—'}</strong></div><div><span>Referência</span><strong>{ceo.referencia||'—'}</strong></div><div><span>Coordenadas</span><strong>{ceo.latitude&&ceo.longitude?`${ceo.latitude}, ${ceo.longitude}`:'—'}</strong></div></div><div className="ceo-actions"><Link to={`/ceos/${ceo.id}`}>Abrir detalhes</Link>{ceo.maps&&<a href={ceo.maps} target="_blank" rel="noreferrer"><MapPin size={16}/>Mapa</a>}{isAdmin&&<button onClick={()=>remover(ceo.id)} title="Excluir"><Trash2 size={16}/></button>}</div></article>)}</div>}
  {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><div className="crud-modal" onMouseDown={e=>e.stopPropagation()}><div className="crud-modal-head"><h2>Nova Caixa de Emenda Óptica</h2><button onClick={()=>setModal(false)}>×</button></div><form className="crud-form" onSubmit={salvar}>{[['nome','Nome da CEO *'],['tipo','Tipo'],['rota','Rota *'],['km','KM'],['latitude','Latitude'],['longitude','Longitude'],['referencia','Referência'],['maps','Google Maps']].map(([n,l])=><label key={n}><span>{l}</span><input value={form[n]} onChange={e=>setForm({...form,[n]:e.target.value})}/></label>)}<label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Operacional</option><option>Atenção</option><option>Rompida</option><option>Desativada</option></select></label><label className="full"><span>Foto da CEO</span><input type="file" accept="image/*" onChange={e=>setForm({...form,foto:e.target.files?.[0]||''})}/><small>{form.foto?.name||'Nenhuma foto selecionada (máx. 700 KB)'}</small></label><label className="full"><span>Observações</span><textarea value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></label><div className="crud-buttons full"><button type="button" className="botao-secundario" onClick={()=>setModal(false)}>Cancelar</button><button className="botao-primario">Salvar CEO</button></div></form></div></div>}
 </div>
}
