import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Building2, MapPin, Plus, Search, Trash2, Pencil } from 'lucide-react';
import useFirestoreCollection from '../hooks/useFirestoreCollection';
import { createRecord, deleteRecord, updateRecord } from '../services/firestoreCrud';
import { useAuth } from '../context/AuthContext';
import './Backbone.css'; import './ClientesDedicados.css';
const vazio={nome:'',rota:'',origem:'',destino:'',velocidade:'',fibra:'',dio:'',portaSwitch:'',vlan:'',ip:'',sfp:'',status:'Ativo',observacao:'',latitude:'',longitude:''};
export default function ClientesDedicados(){
 const {isAdmin}=useAuth();
 const {items,loading,error}=useFirestoreCollection('clientesDedicados',{orderBy:'nome'}); const[q,setQ]=useState('');const[modal,setModal]=useState(false);const[form,setForm]=useState(vazio);const[editingId,setEditingId]=useState(null);const[saving,setSaving]=useState(false);
 const filtrados=useMemo(()=>items.filter(i=>JSON.stringify(i).toLowerCase().includes(q.toLowerCase())),[items,q]);
 function pedirAdmin(){window.dispatchEvent(new CustomEvent('open-admin-login'))}
 function novo(){if(!isAdmin)return pedirAdmin();setEditingId(null);setForm(vazio);setModal(true)}
 function editar(item){if(!isAdmin)return pedirAdmin();setEditingId(item.id);setForm({...vazio,...item});setModal(true)}
 async function salvar(e){e.preventDefault();if(!form.nome.trim())return alert('Informe o cliente.');setSaving(true);try{const data={...form};delete data.id;delete data.criadoEm;delete data.atualizadoEm;if(editingId)await updateRecord('clientesDedicados',editingId,data);else await createRecord('clientesDedicados',data);setForm(vazio);setEditingId(null);setModal(false)}catch(err){console.error(err);alert('Erro ao salvar no Firebase. Verifique o login e as regras.')}finally{setSaving(false)}}
 async function excluir(id){if(!confirm('Excluir este cliente dedicado?'))return;try{await deleteRecord('clientesDedicados',id)}catch(err){console.error(err);alert('Não foi possível excluir.')}}
 return <div className="backbone-page"><div className="backbone-cabecalho"><div><span className="pagina-identificacao">Circuitos corporativos</span><h1>Clientes Dedicados</h1><p>Cada circuito possui mapa, KMZ/KML, dados técnicos e documentação.</p></div><button className={`botao-nova-rota ${!isAdmin?'admin-locked':''}`} onClick={novo} title={!isAdmin?'Entre na Administração para cadastrar':''}><Plus size={18}/> Novo cliente{!isAdmin?' 🔒':''}</button></div><div className="dark-search"><Search size={18}/><input placeholder="Pesquisar cliente, rota, VLAN, IP ou fibra..." value={q} onChange={e=>setQ(e.target.value)}/><span>{filtrados.length} resultado(s)</span></div>{loading?<div className="dark-empty">Carregando da nuvem...</div>:error?<div className="dark-empty">Erro ao carregar o Firebase.</div>:filtrados.length===0?<div className="dark-empty"><Building2 size={42}/><h3>Nenhum cliente dedicado</h3></div>:<div className="backbone-grid">{filtrados.map(item=><article className="rota-card cliente-card" key={item.id}><div className="rota-card-topo"><div className="rota-icone"><Building2 size={23}/></div><span className={`status-rota ${item.status==='Ativo'?'status-operacional':'status-cadastro'}`}>{item.status}</span></div><h2>{item.nome}</h2><p className="nome-completo">{item.rota||`${item.origem||'Origem'} ↔ ${item.destino||'Destino'}`}</p><div className="rota-informacoes"><div><MapPin size={17}/><span><strong>Origem:</strong> {item.origem||'Não informada'}</span></div><div><MapPin size={17}/><span><strong>Destino:</strong> {item.destino||'Não informado'}</span></div><div><Building2 size={17}/><span><strong>VLAN:</strong> {item.vlan||'—'}</span></div><div><Building2 size={17}/><span><strong>Velocidade:</strong> {item.velocidade||'—'}</span></div></div><div className="dark-card-footer"><Link className="botao-abrir-rota" to={`/clientes-dedicados/${item.id}`}>Abrir circuito <ArrowRight size={18}/></Link><button className={`backbone-edit ${!isAdmin?'admin-locked':''}`} onClick={()=>editar(item)} title={!isAdmin?'Entre na Administração para editar':'Editar'}><Pencil size={18}/> Editar{!isAdmin?' 🔒':''}</button>{isAdmin&&<button className="dark-delete" onClick={()=>excluir(item.id)} title="Excluir"><Trash2 size={19}/></button>}</div></article>)}</div>}
 {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><div className="crud-modal" onMouseDown={e=>e.stopPropagation()}><div className="crud-modal-head"><h2>{editingId?'Editar cliente dedicado':'Novo cliente dedicado'}</h2><button onClick={()=>setModal(false)}>×</button></div><form className="crud-form" onSubmit={salvar}>{Object.entries({nome:'Cliente *',rota:'Rota',origem:'Origem',destino:'Destino',velocidade:'Velocidade',fibra:'Fibra / FO',dio:'Porta DIO',portaSwitch:'Porta do switch',vlan:'VLAN',ip:'IP',sfp:'SFP',latitude:'Latitude central',longitude:'Longitude central'}).map(([n,l])=><label key={n}><span>{l}</span><input value={form[n]??''} onChange={e=>setForm({...form,[n]:e.target.value})}/></label>)}<label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Ativo</option><option>Implantação</option><option>Manutenção</option><option>Inativo</option></select></label><label className="full"><span>Observações</span><textarea value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></label><div className="crud-buttons full"><button type="button" className="botao-secundario" onClick={()=>setModal(false)}>Cancelar</button><button className="botao-primario" disabled={saving}>{saving?'Salvando...':editingId?'Salvar alterações':'Salvar cliente'}</button></div></form></div></div>}
 </div>
}
