import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { House, MapPin, Boxes, Cable, Plus, Search, Trash2, ArrowRight } from 'lucide-react';
import useFirestoreCollection from '../hooks/useFirestoreCollection';
import { createRecord, deleteRecord } from '../services/firestoreCrud';
import './FTTH.css';
const vazio={nome:'',cidade:'',descricao:'Rede FTTH urbana',ctos:'0',cabos:'0',olts:'',status:'Operacional',latitude:'',longitude:'',observacao:''};
export default function FTTH(){
 const {items:redes,loading,error}=useFirestoreCollection('ftthRedes',{orderBy:'nome'});const[modal,setModal]=useState(false);const[form,setForm]=useState(vazio);const[q,setQ]=useState('');const[saving,setSaving]=useState(false);
 const filtradas=useMemo(()=>redes.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[redes,q]);
 async function salvar(e){e.preventDefault();if(!form.nome.trim())return alert('Informe o nome da rede FTTH.');setSaving(true);try{await createRecord('ftthRedes',form);setForm(vazio);setModal(false)}catch(err){console.error(err);alert('Erro ao salvar no Firebase.')}finally{setSaving(false)}}
 async function excluir(id){if(!confirm('Excluir esta rede FTTH?'))return;try{await deleteRecord('ftthRedes',id)}catch(err){console.error(err);alert('Não foi possível excluir.')}}
 return <div className="ftth-page"><div className="ftth-cabecalho"><div><span>REDE DE ACESSO</span><h1>FTTH</h1><p>Redes urbanas, CTOs, cabos, OLTs, mapas e arquivos KMZ.</p></div><button onClick={()=>setModal(true)}><Plus size={17}/> Nova rede FTTH</button></div><div className="ftth-toolbar"><Search size={18}/><input placeholder="Pesquisar rede, cidade ou status..." value={q} onChange={e=>setQ(e.target.value)}/><span>{filtradas.length} rede(s)</span></div>{loading?<div className="ftth-empty">Carregando da nuvem...</div>:error?<div className="ftth-empty">Erro ao carregar o Firebase.</div>:<div className="ftth-grid">{filtradas.map(rede=><div className="ftth-card" key={rede.id}><div className="ftth-card-top"><House size={27}/><span>{rede.status}</span></div><h2>{rede.nome}</h2><p>{rede.descricao||'Rede FTTH'}</p><div className="ftth-dados"><span><MapPin size={16}/>{rede.cidade||'Cidade não informada'}</span><span><Boxes size={16}/>CTOs: {rede.ctos||0}</span><span><Cable size={16}/>Cabos: {rede.cabos||0}</span></div><div className="ftth-actions"><Link className="abrir-ftth" to={`/ftth/${rede.id}`}><ArrowRight size={16}/> Abrir rede</Link><button className="excluir-ftth" onClick={()=>excluir(rede.id)}><Trash2 size={16}/></button></div></div>)}</div>}
 {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><div className="crud-modal" onMouseDown={e=>e.stopPropagation()}><div className="crud-modal-head"><h2>Nova rede FTTH</h2><button onClick={()=>setModal(false)}>×</button></div><form className="crud-form" onSubmit={salvar}>{Object.entries({nome:'Nome da rede *',cidade:'Cidade',descricao:'Descrição',ctos:'Quantidade de CTOs',cabos:'Quantidade de cabos',olts:'OLTs',latitude:'Latitude central',longitude:'Longitude central'}).map(([n,l])=><label key={n} className={n==='descricao'?'full':''}><span>{l}</span><input value={form[n]} onChange={e=>setForm({...form,[n]:e.target.value})}/></label>)}<label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Operacional</option><option>Implantação</option><option>Manutenção</option><option>Desativada</option></select></label><label className="full"><span>Observações</span><textarea value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></label><div className="crud-buttons full"><button type="button" className="botao-secundario" onClick={()=>setModal(false)}>Cancelar</button><button className="botao-primario" disabled={saving}>{saving?'Salvando...':'Salvar rede'}</button></div></form></div></div>}
 </div>
}
