import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import {
  ArrowLeft, BatteryCharging, Building2, Camera, ChevronLeft, Download, FileText, Folder, FolderPlus,
  Image as ImageIcon, MapPin, Network, Pencil, Plus, Save, Server, Trash2, Upload, X, Zap
} from 'lucide-react';
import { buscarPOP, atualizarPOP } from '../services/pops';
import { useAuth } from '../context/AuthContext';
import useFirestoreCollection from '../hooks/useFirestoreCollection';
import { createRecord, deleteRecord, updateRecord } from '../services/firestoreCrud';
import { atualizarAnexo, excluirAnexo, observarAnexos, salvarAnexo } from '../services/anexos';
import { criarCaminhoArquivo, deleteFile, uploadFile } from '../services/storage';
import './POPs.css';

const equipamentoVazio = { tipo:'Switch', nome:'', fabricante:'', modelo:'', ip:'', firmware:'', serial:'', observacao:'' };
const energiaVazia = { tipo:'Retificadora', nome:'', modelo:'', tensao:'', capacidade:'', observacao:'' };

function portasVazias(qtd, prefixo='Porta') {
  return Array.from({length:Number(qtd)||0}, (_,i)=>({ numero:i+1, nome:`${prefixo} ${String(i+1).padStart(2,'0')}`, descricao:'' }));
}

export default function POPDetalhes() {
  const { id } = useParams();
  const { isAdmin } = useAuth();
  const [pop,setPop] = useState(null); const [carregando,setCarregando]=useState(true);
  const [editando,setEditando]=useState(false); const [form,setForm]=useState({}); const [salvando,setSalvando]=useState(false);
  const [pastas,setPastas]=useState([]); const [fotos,setFotos]=useState([]); const [documentos,setDocumentos]=useState([]); const [pastaAtiva,setPastaAtiva]=useState(null);
  const [uploading,setUploading]=useState(false); const inputFoto=useRef(null); const inputDocumento=useRef(null);
  const [modalEquip,setModalEquip]=useState(false); const [equipForm,setEquipForm]=useState(equipamentoVazio);
  const [modalEnergia,setModalEnergia]=useState(false); const [energiaForm,setEnergiaForm]=useState(energiaVazia);
  const [modalPortas,setModalPortas]=useState(null); const [portaForm,setPortaForm]=useState({tipo:'dio',nome:'',modelo:'',ip:'',quantidade:24,portas:[]});
  const [editorPortas,setEditorPortas]=useState(null);

  const {items:equipamentos}=useFirestoreCollection('popEquipamentos',{where:[['popId','==',id]]});
  const {items:dios}=useFirestoreCollection('popDios',{where:[['popId','==',id]]});
  const {items:switches}=useFirestoreCollection('popSwitches',{where:[['popId','==',id]]});
  const {items:energia}=useFirestoreCollection('popEnergia',{where:[['popId','==',id]]});

  useEffect(()=>{(async()=>{try{const dados=await buscarPOP(id);setPop(dados);setForm(dados||{});}catch(e){console.error(e)}finally{setCarregando(false)}})()},[id]);
  useEffect(()=>observarAnexos('pop',id,'FOTO_PASTA',setPastas,console.error),[id]);
  useEffect(()=>observarAnexos('pop',id,'FOTO',setFotos,console.error),[id]);
  useEffect(()=>observarAnexos('pop',id,'DOCUMENTO',setDocumentos,console.error),[id]);

  function pedirAdmin(){window.dispatchEvent(new Event('open-admin-login'))}

  async function salvarDados(e){e.preventDefault();if(!isAdmin)return pedirAdmin();setSalvando(true);try{const dados={nome:form.nome||'',sigla:form.sigla||'',cidade:form.cidade||'',endereco:form.endereco||'',latitude:form.latitude||'',longitude:form.longitude||'',maps:form.maps||'',status:form.status||'Operacional',responsavel:form.responsavel||'',telefone:form.telefone||'',observacao:form.observacao||''};await atualizarPOP(id,dados);setPop(p=>({...p,...dados}));setEditando(false)}catch(e){console.error(e);alert('Não foi possível atualizar o POP.')}finally{setSalvando(false)}}

  async function criarPasta(){if(!isAdmin)return pedirAdmin();const nome=prompt('Nome da pasta (ex.: RACK, DIO, FACHADA):');if(!nome?.trim())return;await salvarAnexo({parentType:'pop',parentId:id,categoria:'FOTO_PASTA',nome:nome.trim()})}
  async function renomearPasta(pasta){if(!isAdmin)return pedirAdmin();const nome=prompt('Novo nome:',pasta.nome||'');if(!nome?.trim())return;await atualizarAnexo(pasta.id,{nome:nome.trim()});if(pastaAtiva?.id===pasta.id)setPastaAtiva({...pasta,nome:nome.trim()})}
  async function removerPasta(pasta){if(!isAdmin)return pedirAdmin();const vinculadas=fotos.filter(f=>f.pastaId===pasta.id);if(!confirm(`Excluir a pasta "${pasta.nome}" e ${vinculadas.length} foto(s)?`))return;for(const foto of vinculadas){await deleteFile(foto.storagePath);await excluirAnexo(foto.id)}await excluirAnexo(pasta.id);setPastaAtiva(null)}
  async function enviarFoto(e){if(!isAdmin)return pedirAdmin();const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!pastaAtiva)return alert('Abra uma pasta antes de adicionar foto.');if(!file.type.startsWith('image/'))return alert('Selecione uma imagem.');setUploading(true);try{const path=criarCaminhoArquivo('pops',id,`fotos/${pastaAtiva.id}`,file.name);const up=await uploadFile(path,file);await salvarAnexo({parentType:'pop',parentId:id,categoria:'FOTO',pastaId:pastaAtiva.id,pastaNome:pastaAtiva.nome,nome:file.name,tipo:file.type,tamanho:file.size,url:up.url,storagePath:up.path})}finally{setUploading(false)}}
  async function removerFoto(foto){if(!isAdmin)return pedirAdmin();if(!confirm('Excluir esta foto?'))return;await deleteFile(foto.storagePath);await excluirAnexo(foto.id)}

  async function enviarDocumento(e){if(!isAdmin)return pedirAdmin();const file=e.target.files?.[0];e.target.value='';if(!file)return;setUploading(true);try{const path=criarCaminhoArquivo('pops',id,'documentos',file.name);const up=await uploadFile(path,file);await salvarAnexo({parentType:'pop',parentId:id,categoria:'DOCUMENTO',nome:file.name,tipo:file.type,tamanho:file.size,url:up.url,storagePath:up.path})}finally{setUploading(false)}}
  async function removerDocumento(doc){if(!isAdmin)return pedirAdmin();if(!confirm('Excluir este documento?'))return;await deleteFile(doc.storagePath);await excluirAnexo(doc.id)}

  async function salvarEquip(e){e.preventDefault();if(!isAdmin)return pedirAdmin();try{if(equipForm.id)await updateRecord('popEquipamentos',equipForm.id,{...equipForm,popId:id});else await createRecord('popEquipamentos',{...equipForm,popId:id});setModalEquip(false);setEquipForm(equipamentoVazio)}catch(err){console.error(err);alert('Não foi possível salvar o equipamento.')}}
  async function removerEquip(item){if(!isAdmin)return pedirAdmin();if(confirm(`Excluir ${item.nome||item.tipo}?`))await deleteRecord('popEquipamentos',item.id)}
  async function salvarEnergia(e){e.preventDefault();if(!isAdmin)return pedirAdmin();if(energiaForm.id)await updateRecord('popEnergia',energiaForm.id,{...energiaForm,popId:id});else await createRecord('popEnergia',{...energiaForm,popId:id});setModalEnergia(false);setEnergiaForm(energiaVazia)}
  async function removerEnergia(item){if(!isAdmin)return pedirAdmin();if(confirm(`Excluir ${item.nome||item.tipo}?`))await deleteRecord('popEnergia',item.id)}

  function abrirNovoPortas(tipo){if(!isAdmin)return pedirAdmin();const qtd=tipo==='dio'?24:24;setPortaForm({tipo,nome:tipo==='dio'?'DIO Backbone':'Switch',modelo:'',ip:'',quantidade:qtd,portas:portasVazias(qtd,tipo==='dio'?'FO':'Porta')});setModalPortas(tipo)}
  function alterarQuantidade(qtd){const numero=Math.max(1,Math.min(144,Number(qtd)||1));const atual=portaForm.portas||[];const prefixo=portaForm.tipo==='dio'?'FO':'Porta';setPortaForm({...portaForm,quantidade:numero,portas:Array.from({length:numero},(_,i)=>atual[i]||{numero:i+1,nome:`${prefixo} ${String(i+1).padStart(2,'0')}`,descricao:''})})}
  async function salvarBlocoPortas(e){e.preventDefault();if(!isAdmin)return pedirAdmin();const col=portaForm.tipo==='dio'?'popDios':'popSwitches';const dados={popId:id,nome:portaForm.nome,modelo:portaForm.modelo||'',ip:portaForm.ip||'',quantidade:Number(portaForm.quantidade)||0,portas:portaForm.portas||[]};if(portaForm.id)await updateRecord(col,portaForm.id,dados);else await createRecord(col,dados);setModalPortas(null)}
  function editarBloco(item,tipo){if(!isAdmin)return pedirAdmin();setPortaForm({...item,tipo,portas:Array.isArray(item.portas)?item.portas:portasVazias(item.quantidade,tipo==='dio'?'FO':'Porta')});setModalPortas(tipo)}
  async function removerBloco(item,tipo){if(!isAdmin)return pedirAdmin();if(!confirm(`Excluir ${item.nome}?`))return;await deleteRecord(tipo==='dio'?'popDios':'popSwitches',item.id)}
  function abrirEditor(item,tipo){setEditorPortas({...item,tipo,portas:Array.isArray(item.portas)?item.portas:[]})}
  async function salvarEditorPortas(){if(!isAdmin)return pedirAdmin();await updateRecord(editorPortas.tipo==='dio'?'popDios':'popSwitches',editorPortas.id,{portas:editorPortas.portas});setEditorPortas(null)}

  const fotosAtivas=useMemo(()=>fotos.filter(f=>f.pastaId===pastaAtiva?.id),[fotos,pastaAtiva]);

  if(carregando)return <div className="pops-empty">Carregando POP...</div>;
  if(!pop)return <div className="pops-empty"><h2>POP não encontrado</h2><Link to="/pops">Voltar</Link></div>;

  return <div className="pop-detail-page">
    <Link className="pop-back" to="/pops"><ArrowLeft size={17}/> Voltar para POPs</Link>
    <header className="pop-detail-header"><div><span className="pagina-identificacao">PONTO DE PRESENÇA</span><h1>{pop.nome}</h1><p>{pop.sigla ? `${pop.sigla} · ` : ''}{pop.cidade || 'Cidade não informada'}</p></div><div className="pop-head-actions"><span className="pop-status operacional">{pop.status}</span>{isAdmin && !editando && <button className="botao-primario" onClick={()=>setEditando(true)}><Pencil size={17}/> Editar</button>}</div></header>

    {editando ? <form className="pop-panel pop-edit-form" onSubmit={salvarDados}><div className="pop-section-head"><div><h2><Pencil size={20}/> Editar POP</h2></div><div className="pop-inline-actions"><button type="button" className="botao-secundario" onClick={()=>{setForm(pop);setEditando(false)}}><X size={16}/> Cancelar</button><button className="botao-primario" disabled={salvando}><Save size={16}/> {salvando?'Salvando...':'Salvar'}</button></div></div><div className="pop-form-grid">{[['nome','Nome'],['sigla','Sigla'],['cidade','Cidade'],['endereco','Endereço'],['latitude','Latitude'],['longitude','Longitude'],['maps','Google Maps'],['responsavel','Responsável'],['telefone','Telefone']].map(([n,l])=><label key={n}>{l}<input value={form[n]||''} onChange={e=>setForm({...form,[n]:e.target.value})}/></label>)}<label>Status<select value={form.status||'Operacional'} onChange={e=>setForm({...form,status:e.target.value})}><option>Operacional</option><option>Manutenção</option><option>Atenção</option><option>Inativo</option></select></label><label className="full">Observações<textarea rows="4" value={form.observacao||''} onChange={e=>setForm({...form,observacao:e.target.value})}/></label></div></form> : <div className="pop-info-grid"><section className="pop-panel"><h2><Building2 size={20}/> Informações</h2><dl><div><dt>Sigla</dt><dd>{pop.sigla||'—'}</dd></div><div><dt>Cidade</dt><dd>{pop.cidade||'—'}</dd></div><div><dt>Endereço</dt><dd>{pop.endereco||'—'}</dd></div><div><dt>Responsável</dt><dd>{pop.responsavel||'—'}</dd></div><div><dt>Telefone</dt><dd>{pop.telefone||'—'}</dd></div><div><dt>Observações</dt><dd>{pop.observacao||'—'}</dd></div></dl></section><section className="pop-panel"><h2><MapPin size={20}/> Localização</h2><dl><div><dt>Latitude</dt><dd>{pop.latitude||'—'}</dd></div><div><dt>Longitude</dt><dd>{pop.longitude||'—'}</dd></div></dl>{pop.maps&&<a className="pop-map-button" href={pop.maps} target="_blank" rel="noreferrer"><MapPin size={16}/> Abrir no Google Maps</a>}</section></div>}

    <div className="pop-summary"><div><Server/><span><strong>{equipamentos.length}</strong>Equipamentos</span></div><div><Network/><span><strong>{dios.length}</strong>DIOs</span></div><div><Network/><span><strong>{switches.length}</strong>Switches</span></div><div><Camera/><span><strong>{fotos.length}</strong>Fotos</span></div></div>

    <section className="pop-panel"><div className="pop-section-head"><div><h2><Camera size={20}/> Fotos do POP</h2><p>Separe por fachada, rack, DIO, switch, OLT, energia ou qualquer outro local.</p></div>{isAdmin && (!pastaAtiva?<button className="botao-primario" onClick={criarPasta}><FolderPlus size={17}/> Nova pasta</button>:<button className="botao-primario" onClick={()=>inputFoto.current?.click()} disabled={uploading}><Upload size={17}/> {uploading?'Enviando...':'Adicionar foto'}</button>)}</div><input ref={inputFoto} type="file" accept="image/*" hidden onChange={enviarFoto}/>
      {!pastaAtiva ? <div className="pop-folder-grid">{pastas.length===0?<div className="pops-empty compact"><Folder size={36}/><p>Nenhuma pasta criada.</p></div>:pastas.map(p=><article key={p.id}><button className="pop-folder-open" onClick={()=>setPastaAtiva(p)}><Folder size={30}/><span><strong>{p.nome}</strong><small>{fotos.filter(f=>f.pastaId===p.id).length} foto(s)</small></span></button>{isAdmin&&<div className="pop-folder-actions"><button onClick={()=>renomearPasta(p)}><Pencil size={15}/></button><button className="danger" onClick={()=>removerPasta(p)}><Trash2 size={15}/></button></div>}</article>)}</div> : <><div className="pop-folder-toolbar"><button className="botao-secundario" onClick={()=>setPastaAtiva(null)}><ChevronLeft size={16}/> Voltar</button><strong><Folder size={18}/>{pastaAtiva.nome}</strong></div>{fotosAtivas.length===0?<div className="pops-empty compact"><ImageIcon size={36}/><p>Nenhuma foto nesta pasta.</p></div>:<div className="pop-photo-grid">{fotosAtivas.map(f=><article key={f.id}><a href={f.url} target="_blank" rel="noreferrer"><img src={f.url} alt={f.nome}/></a><div><span>{f.nome}</span>{isAdmin&&<button className="danger" onClick={()=>removerFoto(f)}><Trash2 size={16}/></button>}</div></article>)}</div>}</>}
    </section>

    <section className="pop-panel"><div className="pop-section-head"><div><h2><Server size={20}/> Equipamentos</h2><p>Switches, OLTs, roteadores, Datacom, nobreaks e outros equipamentos.</p></div>{isAdmin&&<button className="botao-primario" onClick={()=>{setEquipForm(equipamentoVazio);setModalEquip(true)}}><Plus size={17}/> Equipamento</button>}</div><div className="pop-card-grid">{equipamentos.length===0?<div className="pops-empty compact">Nenhum equipamento cadastrado.</div>:equipamentos.map(item=><article className="pop-mini-card" key={item.id}><div><Server size={20}/><span><strong>{item.nome||item.tipo}</strong><small>{item.tipo} · {item.modelo||'Modelo não informado'}</small></span></div><dl><div><dt>IP</dt><dd>{item.ip||'—'}</dd></div><div><dt>Fabricante</dt><dd>{item.fabricante||'—'}</dd></div></dl>{isAdmin&&<div className="pop-mini-actions"><button onClick={()=>{setEquipForm(item);setModalEquip(true)}}><Pencil size={15}/></button><button className="danger" onClick={()=>removerEquip(item)}><Trash2 size={15}/></button></div>}</article>)}</div></section>

    <section className="pop-panel"><div className="pop-section-head"><div><h2><Network size={20}/> DIOs e portas</h2><p>Cadastre o DIO e descreva cada fibra/porta.</p></div>{isAdmin&&<button className="botao-primario" onClick={()=>abrirNovoPortas('dio')}><Plus size={17}/> Novo DIO</button>}</div><div className="pop-card-grid">{dios.length===0?<div className="pops-empty compact">Nenhum DIO cadastrado.</div>:dios.map(item=><article className="pop-mini-card" key={item.id}><div><Network size={20}/><span><strong>{item.nome}</strong><small>{item.quantidade||0} portas</small></span></div><button className="pop-open-ports" onClick={()=>abrirEditor(item,'dio')}>Abrir portas</button>{isAdmin&&<div className="pop-mini-actions"><button onClick={()=>editarBloco(item,'dio')}><Pencil size={15}/></button><button className="danger" onClick={()=>removerBloco(item,'dio')}><Trash2 size={15}/></button></div>}</article>)}</div></section>

    <section className="pop-panel"><div className="pop-section-head"><div><h2><Network size={20}/> Switches e portas</h2><p>Documente as portas dos switches e o destino de cada conexão.</p></div>{isAdmin&&<button className="botao-primario" onClick={()=>abrirNovoPortas('switch')}><Plus size={17}/> Novo switch</button>}</div><div className="pop-card-grid">{switches.length===0?<div className="pops-empty compact">Nenhum switch cadastrado.</div>:switches.map(item=><article className="pop-mini-card" key={item.id}><div><Network size={20}/><span><strong>{item.nome}</strong><small>{item.modelo||'Modelo não informado'} · {item.quantidade||0} portas</small></span></div>{item.ip&&<small>IP: {item.ip}</small>}<button className="pop-open-ports" onClick={()=>abrirEditor(item,'switch')}>Abrir portas</button>{isAdmin&&<div className="pop-mini-actions"><button onClick={()=>editarBloco(item,'switch')}><Pencil size={15}/></button><button className="danger" onClick={()=>removerBloco(item,'switch')}><Trash2 size={15}/></button></div>}</article>)}</div></section>

    <section className="pop-panel"><div className="pop-section-head"><div><h2><Zap size={20}/> Energia</h2><p>Retificadoras, baterias, nobreaks, geradores e alimentação do POP.</p></div>{isAdmin&&<button className="botao-primario" onClick={()=>{setEnergiaForm(energiaVazia);setModalEnergia(true)}}><Plus size={17}/> Item de energia</button>}</div><div className="pop-card-grid">{energia.length===0?<div className="pops-empty compact">Nenhum item de energia cadastrado.</div>:energia.map(item=><article className="pop-mini-card" key={item.id}><div><BatteryCharging size={20}/><span><strong>{item.nome||item.tipo}</strong><small>{item.modelo||item.tipo}</small></span></div><dl><div><dt>Tensão</dt><dd>{item.tensao||'—'}</dd></div><div><dt>Capacidade</dt><dd>{item.capacidade||'—'}</dd></div></dl>{isAdmin&&<div className="pop-mini-actions"><button onClick={()=>{setEnergiaForm(item);setModalEnergia(true)}}><Pencil size={15}/></button><button className="danger" onClick={()=>removerEnergia(item)}><Trash2 size={15}/></button></div>}</article>)}</div></section>

    <section className="pop-panel"><div className="pop-section-head"><div><h2><FileText size={20}/> Documentos</h2><p>Projetos, manuais, diagramas, PDFs, KMZ e outros arquivos do POP.</p></div>{isAdmin&&<button className="botao-primario" onClick={()=>inputDocumento.current?.click()} disabled={uploading}><Upload size={17}/> Adicionar arquivo</button>}</div><input ref={inputDocumento} type="file" hidden onChange={enviarDocumento}/><div className="pop-doc-list">{documentos.length===0?<div className="pops-empty compact">Nenhum documento cadastrado.</div>:documentos.map(d=><article key={d.id}><div><FileText size={18}/><span><strong>{d.nome}</strong><small>{d.tamanho?`${Math.round(d.tamanho/1024)} KB`:''}</small></span></div><div><a href={d.url} target="_blank" rel="noreferrer"><Download size={16}/> Abrir</a>{isAdmin&&<button className="danger" onClick={()=>removerDocumento(d)}><Trash2 size={16}/></button>}</div></article>)}</div></section>

    {modalEquip&&<div className="modal-backdrop" onMouseDown={()=>setModalEquip(false)}><div className="crud-modal" onMouseDown={e=>e.stopPropagation()}><div className="crud-modal-head"><h2>{equipForm.id?'Editar equipamento':'Novo equipamento'}</h2><button onClick={()=>setModalEquip(false)}>×</button></div><form className="crud-form" onSubmit={salvarEquip}>{[['nome','Nome'],['tipo','Tipo'],['fabricante','Fabricante'],['modelo','Modelo'],['ip','IP'],['firmware','Firmware'],['serial','Número de série']].map(([n,l])=><label key={n}><span>{l}</span><input value={equipForm[n]||''} onChange={e=>setEquipForm({...equipForm,[n]:e.target.value})}/></label>)}<label className="full"><span>Observações</span><textarea value={equipForm.observacao||''} onChange={e=>setEquipForm({...equipForm,observacao:e.target.value})}/></label><div className="crud-buttons full"><button type="button" className="botao-secundario" onClick={()=>setModalEquip(false)}>Cancelar</button><button className="botao-primario">Salvar</button></div></form></div></div>}

    {modalEnergia&&<div className="modal-backdrop" onMouseDown={()=>setModalEnergia(false)}><div className="crud-modal" onMouseDown={e=>e.stopPropagation()}><div className="crud-modal-head"><h2>{energiaForm.id?'Editar energia':'Novo item de energia'}</h2><button onClick={()=>setModalEnergia(false)}>×</button></div><form className="crud-form" onSubmit={salvarEnergia}>{[['nome','Nome'],['tipo','Tipo'],['modelo','Modelo'],['tensao','Tensão'],['capacidade','Capacidade']].map(([n,l])=><label key={n}><span>{l}</span><input value={energiaForm[n]||''} onChange={e=>setEnergiaForm({...energiaForm,[n]:e.target.value})}/></label>)}<label className="full"><span>Observações</span><textarea value={energiaForm.observacao||''} onChange={e=>setEnergiaForm({...energiaForm,observacao:e.target.value})}/></label><div className="crud-buttons full"><button type="button" className="botao-secundario" onClick={()=>setModalEnergia(false)}>Cancelar</button><button className="botao-primario">Salvar</button></div></form></div></div>}

    {modalPortas&&<div className="modal-backdrop" onMouseDown={()=>setModalPortas(null)}><div className="crud-modal" onMouseDown={e=>e.stopPropagation()}><div className="crud-modal-head"><h2>{portaForm.id?'Editar':'Novo'} {modalPortas==='dio'?'DIO':'switch'}</h2><button onClick={()=>setModalPortas(null)}>×</button></div><form className="crud-form" onSubmit={salvarBlocoPortas}><label><span>Nome</span><input value={portaForm.nome||''} onChange={e=>setPortaForm({...portaForm,nome:e.target.value})}/></label><label><span>Modelo</span><input value={portaForm.modelo||''} onChange={e=>setPortaForm({...portaForm,modelo:e.target.value})}/></label>{modalPortas==='switch'&&<label><span>IP</span><input value={portaForm.ip||''} onChange={e=>setPortaForm({...portaForm,ip:e.target.value})}/></label>}<label><span>Quantidade de portas</span><input type="number" min="1" max="144" value={portaForm.quantidade} onChange={e=>alterarQuantidade(e.target.value)}/></label><div className="crud-buttons full"><button type="button" className="botao-secundario" onClick={()=>setModalPortas(null)}>Cancelar</button><button className="botao-primario">Salvar</button></div></form></div></div>}

    {editorPortas&&<div className="modal-backdrop ports-backdrop" onMouseDown={()=>setEditorPortas(null)}><div className="pop-ports-modal" onMouseDown={e=>e.stopPropagation()}><div className="crud-modal-head"><div><h2>{editorPortas.nome}</h2><p>{editorPortas.quantidade} portas</p></div><button onClick={()=>setEditorPortas(null)}>×</button></div><div className="pop-ports-grid">{editorPortas.portas.map((porta,index)=><label key={index}><span>{porta.nome||`Porta ${index+1}`}</span><input disabled={!isAdmin} placeholder="Destino / circuito / observação" value={porta.descricao||''} onChange={e=>{const novas=[...editorPortas.portas];novas[index]={...novas[index],descricao:e.target.value};setEditorPortas({...editorPortas,portas:novas})}}/></label>)}</div><div className="pop-ports-footer"><button className="botao-secundario" onClick={()=>setEditorPortas(null)}>Fechar</button>{isAdmin&&<button className="botao-primario" onClick={salvarEditorPortas}><Save size={16}/> Salvar portas</button>}</div></div></div>}
  </div>;
}
